// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Test1

#include "../ui.h"

void ui_comp_Comp_DeviceItem_create_hook(lv_obj_t * comp)
{
}
