// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Test1

#include "../ui.h"

// COMPONENT Comp_DeviceItem

lv_obj_t * ui_Comp_DeviceItem_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Comp_DeviceItem;
    cui_Comp_DeviceItem = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_Comp_DeviceItem, 100);
    lv_obj_set_width(cui_Comp_DeviceItem, lv_pct(100));
    lv_obj_set_align(cui_Comp_DeviceItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Comp_DeviceItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Comp_DeviceItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Comp_DeviceItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Panel7;
    cui_Panel7 = lv_obj_create(cui_Comp_DeviceItem);
    lv_obj_set_width(cui_Panel7, 814);
    lv_obj_set_height(cui_Panel7, lv_pct(100));
    lv_obj_set_x(cui_Panel7, -4);
    lv_obj_set_y(cui_Panel7, -43);
    lv_obj_set_flex_flow(cui_Panel7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Panel7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(cui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label3;
    cui_Label3 = lv_label_create(cui_Panel7);
    lv_obj_set_width(cui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label3, -2);
    lv_obj_set_y(cui_Label3, -4);
    lv_obj_set_align(cui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label3, "Device Name");

    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(cui_Panel7);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label4, "00:00:00:00");

    lv_obj_t * cui_Button5;
    cui_Button5 = lv_button_create(cui_Comp_DeviceItem);
    lv_obj_set_width(cui_Button5, 100);
    lv_obj_set_height(cui_Button5, 50);
    lv_obj_set_x(cui_Button5, 447);
    lv_obj_set_y(cui_Button5, 1);
    lv_obj_set_align(cui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label5;
    cui_Label5 = lv_label_create(cui_Button5);
    lv_obj_set_width(cui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label5, "连接");
    lv_obj_set_style_text_font(cui_Label5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_COMP_DEVICEITEM_NUM);
    children[UI_COMP_COMP_DEVICEITEM_COMP_DEVICEITEM] = cui_Comp_DeviceItem;
    children[UI_COMP_COMP_DEVICEITEM_PANEL7] = cui_Panel7;
    children[UI_COMP_COMP_DEVICEITEM_PANEL7_LABEL3] = cui_Label3;
    children[UI_COMP_COMP_DEVICEITEM_PANEL7_LABEL4] = cui_Label4;
    children[UI_COMP_COMP_DEVICEITEM_BUTTON5] = cui_Button5;
    children[UI_COMP_COMP_DEVICEITEM_BUTTON5_LABEL5] = cui_Label5;
    lv_obj_add_event_cb(cui_Comp_DeviceItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Comp_DeviceItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Comp_DeviceItem_create_hook(cui_Comp_DeviceItem);
    return cui_Comp_DeviceItem;
}

