// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Test1

#ifndef _UI_COMP_COMP_DEVICEITEM_H
#define _UI_COMP_COMP_DEVICEITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Comp_DeviceItem
#define UI_COMP_COMP_DEVICEITEM_COMP_DEVICEITEM 0
#define UI_COMP_COMP_DEVICEITEM_PANEL7 1
#define UI_COMP_COMP_DEVICEITEM_PANEL7_LABEL3 2
#define UI_COMP_COMP_DEVICEITEM_PANEL7_LABEL4 3
#define UI_COMP_COMP_DEVICEITEM_BUTTON5 4
#define UI_COMP_COMP_DEVICEITEM_BUTTON5_LABEL5 5
#define _UI_COMP_COMP_DEVICEITEM_NUM 6
lv_obj_t * ui_Comp_DeviceItem_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
