// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Test1

#include "ui.h"
#include "stdio.h"

void ConnectClicked(lv_event_t * e)
{
	printf("ConnectClicked\n");
	// Your code here
}

void ScanClicked(lv_event_t * e)
{
	printf("ScanClicked\n");
	// Your code here
}
